apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infinitedb.fullname" . }}
  labels:
    {{- include "infinitedb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "infinitedb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "infinitedb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "infinitedb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- if .Values.config.databasePath }}
            - name: DATABASE_PATH
              value: {{ .Values.config.databasePath | quote }}
            {{- end }}
            {{- if .Values.config.authentication }}
            - name: AUTHENTICATION
              value: {{ .Values.config.authentication | quote }}
            {{- end }}
            {{- if .Values.config.port }}
            - name: PORT
              value: {{ .Values.config.port | quote }}
            {{- end }}
            {{- if .Values.config.requestLogging }}
            - name: REQUEST_LOGGING
              value: {{ .Values.config.requestLogging | quote }}
            {{- end }}
            {{- if .Values.config.cacheSize }}
            - name: CACHE_SIZE
              value: {{ .Values.config.cacheSize | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
            - name: data
              persistentVolumeClaim:
                claimName: {{ tpl .Values.persistence.existingClaim $ }}
        {{- else }}
          - name: data
            emptyDir: { }
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
